-- Criar tabela TB_PEDIDO somente se não existir
CREATE TABLE IF NOT EXISTS TB_PEDIDO (
    ID_PEDIDO SERIAL PRIMARY KEY, -- Identificador único do pedido
    ST_PEDIDO VARCHAR(50) NOT NULL, -- Status do pedido (PENDENTE, CONFIRMADO, CANCELADO, ENTREGUE)
    TP_CANAL VARCHAR(50) NOT NULL, -- Tipo de canal pelo qual o pedido foi feito (APLICATIVO, SITE, MARKETPLACE)
    TS_CRIACAO TIMESTAMP NOT NULL, -- Timestamp de criação do pedido (gerenciado pela aplicação)
    PC_PEDIDO NUMERIC(10, 2) NOT NULL, -- Valor total do pedido
    NU_PEDIDO VARCHAR(50) -- Número do pedido externo
);

-- Criar tabela TB_ITENS somente se não existir
CREATE TABLE IF NOT EXISTS TB_ITENS (
    ID_PEDIDO BIGINT NOT NULL,
    NU_ITEM INT NOT NULL,
    ID_PRODUTO BIGINT NOT NULL,
    NO_PRODUTO VARCHAR(255) NOT NULL,
    DS_ATRIBUTOS VARCHAR(255),
    DS_DESCRICAO VARCHAR(255),
    QT_PRODUTO INT NOT NULL,
    PC_PRODUTO DECIMAL(10, 2) NOT NULL,
    PRIMARY KEY (ID_PEDIDO, NU_ITEM),
    CONSTRAINT FK_TB_ITENS_PEDIDO FOREIGN KEY (ID_PEDIDO)
        REFERENCES TB_PEDIDO(ID_PEDIDO)
);

-- Criar índice IDX_TB_ITENS_ID_PRODUTO somente se não existir
CREATE INDEX IF NOT EXISTS IDX_TB_ITENS_ID_PRODUTO ON TB_ITENS (ID_PRODUTO);
